server:
  port: 80
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: admin-service_router
          uri: lb://admin-service   # 转发到那个目的地
          predicates:
            - Path=/admin/**
        - id: test_router
          uri: http://www.aliyun.com
          predicates:
            - Path=/product
    # 通过网关来完成对2种维度的限流： 网关维度 + API 分组
    sentinel:
      filter:
        enabled: true
#      transport:
#        dashboard: sentinel-server:8858  # sentinel-dashboard 放在ecs 里面
      datasource:
        ds1.file:
          file: classpath:gw-flow.json
          ruleType: gw_flow
        ds2.file:
          file: classpath:api-group.json
          ruleType: gw_api_group